shell = { program = "sh", args = [ "-l", "-c", "tmux"] }

[font]
size = 20
normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }

[keyboard]
bindings = [
	{ key = "Left", mods = "Alt", chars = "\u001BB" }, # Skip word left
	{ key = "Right", mods = "Alt", chars = "\u001BF" }, # Skip word right
]

