font = { size = 20 }

shell = { program = "tmux" }

key_bindings = [
	{ key = "Left", mods = "Alt", chars = "\u001BB" }, # Skip word left
	{ key = "Right", mods = "Alt", chars = "\u001BF" }, # Skip word right
]
