---Default keymap hints
---@type { lhs: string, desc: string, help: string }[]
local M = {
	{ lhs = "<C-S>",        desc = "Signature help (insert)",   help = "i_CTRL-S" },
	{ lhs = "<C-W>d",       desc = "Diagnostic float",          help = "CTRL-W_d" },
	{ lhs = "<C-x><C-]>",   desc = "Tags completion",           help = "i_CTRL-X_C-]" },
	{ lhs = "<C-x><C-f>",   desc = "File name completion",      help = "i_CTRL-X_CTRL-F" },
	{ lhs = "<C-x><C-i>",   desc = "Include file completion",   help = "i_CTRL-X_CTRL-I" },
	{ lhs = "<C-x><C-k>",   desc = "Dictionary completion",     help = "i_CTRL-X_CTRL-K" },
	{ lhs = "<C-x><C-l>",   desc = "Whole line completion",     help = "i_CTRL-X_CTRL-L" },
	{ lhs = "<C-x><C-n>",   desc = "Keyword completion",        help = "i_CTRL-X_CTRL-N" },
	{ lhs = "<C-x><C-o>",   desc = "Omni completion",           help = "i_CTRL-X_CTRL-O" },
	{ lhs = "<C-x><C-s>",   desc = "Spelling suggestion",       help = "i_CTRL-X_CTRL-S" },
	{ lhs = "<C-x><C-t>",   desc = "Thesaurus completion",      help = "i_CTRL-X_CTRL-T" },
	{ lhs = "<C-x><C-u>",   desc = "User completion",           help = "i_CTRL-X_CTRL-U" },
	{ lhs = "<C-x><C-v>",   desc = "Vim command completion",    help = "i_CTRL-X_CTRL-V" },
	{ lhs = "<leader>f",    desc = "Format buffer",             help = "lsp" },
	{ lhs = "<leader>gD",   desc = "Go to declaration",         help = "lsp" },
	{ lhs = "<leader>gd",   desc = "Go to definition",          help = "lsp" },
	{ lhs = "K",            desc = "Hover documentation",       help = "K" },
	{ lhs = "ZQ",           desc = "Quit without saving",       help = "ZQ" },
	{ lhs = "ZR",           desc = "Restart Nvim",              help = "ZR" },
	{ lhs = "ZZ",           desc = "Save and quit",             help = "ZZ" },
	{ lhs = "[D",           desc = "First diagnostic",          help = "[D" },
	{ lhs = "[d",           desc = "Previous diagnostic",       help = "[d" },
	{ lhs = "[s",           desc = "Previous misspelling",      help = "[s" },
	{ lhs = "]D",           desc = "Last diagnostic",           help = "]D" },
	{ lhs = "]d",           desc = "Next diagnostic",           help = "]d" },
	{ lhs = "]s",           desc = "Next misspelling",          help = "]s" },
	{ lhs = "gO",           desc = "Document symbols",          help = "gO" },
	{ lhs = "gcc",          desc = "Comment",                   help = "gri" },
	{ lhs = "gra",          desc = "Code action",               help = "gra" },
	{ lhs = "gri",          desc = "Implementation",            help = "gri" },
	{ lhs = "grn",          desc = "Rename symbol",             help = "grn" },
	{ lhs = "grr",          desc = "References",                help = "grr" },
	{ lhs = "grt",          desc = "Type definition",           help = "grt" },
	{ lhs = "z=",           desc = "Spell suggest",             help = "z=" },
	{ lhs = "zA",           desc = "Toggle folds recursively",  help = "fold-commands" },
	{ lhs = "zC",           desc = "Close folds recursively",   help = "fold-commands" },
	{ lhs = "zM",           desc = "Close all folds",           help = "fold-commands" },
	{ lhs = "zO",           desc = "Open folds recursively",    help = "fold-commands" },
	{ lhs = "zR",           desc = "Open all folds",            help = "fold-commands" },
	{ lhs = "za",           desc = "Toggle fold",               help = "fold-commands" },
	{ lhs = "zc",           desc = "Close fold",                help = "fold-commands" },
	{ lhs = "zi",           desc = "Toggle folding on/off",     help = "fold-commands" },
	{ lhs = "zm",           desc = "Fold more",                 help = "fold-commands" },
	{ lhs = "zo",           desc = "Open fold",                 help = "fold-commands" },
	{ lhs = "zr",           desc = "Reduce fold level",         help = "fold-commands" },
	{ lhs = "zv",           desc = "Open folds for cursor",     help = "fold-commands" },
	{ lhs = "zx",           desc = "Re-apply foldlevel",        help = "fold-commands" },
}

return M
